# runtime: python39
# entrypoint: gunicorn -b :$PORT backend.app:app

# handlers:
# - url: /static
# static_dir: static

# - url: /static/images
#   static_dir: static/images

# - url: /.*
#   script: auto

runtime: python39

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto
